/** Pixel icons, drawn on a 12 x 12 grid. X is a filled pixel. */
const ART = {
  flag: [
    'X...........',
    'XXX.XX.XX...',
    'XXX.XX.XX...',
    'X..XX.XX.XX.',
    'X..XX.XX.XX.',
    'XXX.XX.XX...',
    'XXX.XX.XX...',
    'X...........',
    'X...........',
    'X...........',
    'X...........',
    'X...........',
  ],
  wrench: [
    '........XX..',
    '.......XX...',
    '.......XX..X',
    '.......XXXXX',
    '......XXXXX.',
    '.....XXX....',
    '....XXX.....',
    '...XXX......',
    '..XXX.......',
    '.XXX........',
    'XXX.........',
    'XX..........',
  ],
  tune: [
    '.X...X....X.',
    '.X...X....X.',
    '.X..XXX...X.',
    '.X..XXX...X.',
    '.X...X...XXX',
    '.X...X...XXX',
    'XXX..X....X.',
    'XXX..X....X.',
    '.X...X....X.',
    '.X...X....X.',
    '.X...X....X.',
    '............',
  ],
  helmet: [
    '...XXXXXX...',
    '..XXXXXXXX..',
    '.XXXXXXXXXX.',
    '.XXXXXXXXXX.',
    'XXXXX.......',
    'XXXXX.......',
    'XXXXXXXXXXX.',
    'XXXXXXXXXXX.',
    '.XXXXXXXXXX.',
    '.XXXXXXXXX..',
    '..XXXXXXX...',
    '............',
  ],
  trophy: [
    '..XXXXXXXX..',
    'XXXXXXXXXXXX',
    'X.XXXXXXXX.X',
    'X.XXXXXXXX.X',
    '.XXXXXXXXXX.',
    '...XXXXXX...',
    '....XXXX....',
    '.....XX.....',
    '.....XX.....',
    '....XXXX....',
    '..XXXXXXXX..',
    '..XXXXXXXX..',
  ],
  online: [
    '............',
    '.X........X.',
    'X..X....X..X',
    'X.X..XX..X.X',
    'X.X..XX..X.X',
    'X..X.XX.X..X',
    '.X...XX...X.',
    '.....XX.....',
    '.....XX.....',
    '.....XX.....',
    '....XXXX....',
    '...XXXXXX...',
  ],
  sound: [
    '.....X......',
    '....XX...X..',
    '...XXX....X.',
    'XXXXXX.X..X.',
    'XXXXXX..X.X.',
    'XXXXXX..X.X.',
    'XXXXXX..X.X.',
    'XXXXXX.X..X.',
    '...XXX....X.',
    '....XX...X..',
    '.....X......',
    '............',
  ],
  mute: [
    '.....X......',
    '....XX......',
    '...XXX......',
    'XXXXXX.X...X',
    'XXXXXX..X.X.',
    'XXXXXX...X..',
    'XXXXXX..X.X.',
    'XXXXXX.X...X',
    '...XXX......',
    '....XX......',
    '.....X......',
    '............',
  ],
  key: [
    '............',
    '............',
    '.XXXX.......',
    'XX..XX......',
    'X....X......',
    'X....XXXXXXX',
    'X....XXXXXXX',
    'XX..XX..X.X.',
    '.XXXX...X.X.',
    '............',
    '............',
    '............',
  ],
  car: [
    '............',
    '............',
    '...XXXXXX...',
    '..XX....XX..',
    '.XX......XX.',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    '.XXX....XXX.',
    '.XXX....XXX.',
    '............',
    '............',
  ],
  circuit: [
    '..XXXXXXX...',
    '.XX.....XX..',
    'XX.......XX.',
    'X.........X.',
    'X....XXXXXX.',
    'X....X......',
    'XX...XXXXX..',
    '.XX......XX.',
    '..XX......X.',
    '...XX....XX.',
    '....XXXXXX..',
    '............',
  ],
  rules: [
    'XX.XXXXXXXXX',
    'XX.XXXXXXXXX',
    '............',
    'XX.XXXXXXX..',
    'XX.XXXXXXX..',
    '............',
    'XX.XXXXXXXXX',
    'XX.XXXXXXXXX',
    '............',
    'XX.XXXXX....',
    'XX.XXXXX....',
    '............',
  ],
  headset: [
    '...XXXXXX...',
    '..XX....XX..',
    '.XX......XX.',
    '.X........X.',
    'XXX......XXX',
    'XXX......XXX',
    'XXX......XXX',
    'XXX......XX.',
    '.........X..',
    '......XXXX..',
    '......XX....',
    '............',
  ],
  marshal: [
    'X...........',
    'XXXXXXX.....',
    'XXXXXXXXXXX.',
    'XXXXXXXXXXX.',
    'XXXXXXXXXXX.',
    'XXXXXXXXXXX.',
    'X...XXXXXXX.',
    'X...........',
    'X...........',
    'X...........',
    'X...........',
    'X...........',
  ],
  sun: [
    '.....XX.....',
    '.X...XX...X.',
    '..X......X..',
    '....XXXX....',
    '...XXXXXX...',
    'XX.XXXXXX.XX',
    'XX.XXXXXX.XX',
    '...XXXXXX...',
    '....XXXX....',
    '..X......X..',
    '.X...XX...X.',
    '.....XX.....',
  ],
  rain: [
    '....XXXX....',
    '..XXXXXXXX..',
    '.XXXXXXXXXX.',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    '.XXXXXXXXXX.',
    '............',
    '..X..X..X...',
    '.X..X..X....',
    '............',
    '...X..X..X..',
    '..X..X..X...',
  ],
  snow: [
    '.....XX.....',
    '.X...XX...X.',
    '..X..XX..X..',
    '...X.XX.X...',
    '....XXXX....',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    '....XXXX....',
    '...X.XX.X...',
    '..X..XX..X..',
    '.X...XX...X.',
    '.....XX.....',
  ],
  camera: [
    '............',
    '....XXXX....',
    'XXXXXXXXXXXX',
    'XXXX....XXXX',
    'XXX..XX..XXX',
    'XXX.XXXX.XXX',
    'XXX.XXXX.XXX',
    'XXX..XX..XXX',
    'XXXX....XXXX',
    'XXXXXXXXXXXX',
    '............',
    '............',
  ],
  gauge: [
    '............',
    '...XXXXXX...',
    '.XXX....XXX.',
    '.X.......XX.',
    'XX......X.XX',
    'X......X...X',
    'X....XX....X',
    'X....XX....X',
    'XX........XX',
    '.XXXXXXXXXX.',
    '............',
    '............',
  ],
  chart: [
    'X...........',
    'X.........X.',
    'X........XX.',
    'X.....X.XX..',
    'X....XXXX...',
    'X...XX.X....',
    'X.XXX.......',
    'X.X.........',
    'X...........',
    'X...........',
    'XXXXXXXXXXXX',
    '............',
  ],
  user: [
    '....XXXX....',
    '...XXXXXX...',
    '...XXXXXX...',
    '...XXXXXX...',
    '....XXXX....',
    '............',
    '..XXXXXXXX..',
    '.XXXXXXXXXX.',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    'XXXXXXXXXXXX',
    '............',
  ],
  star: [
    '.....XX.....',
    '.....XX.....',
    '....XXXX....',
    'XXXXXXXXXXXX',
    '.XXXXXXXXXX.',
    '..XXXXXXXX..',
    '..XXXXXXXX..',
    '.XXXX..XXXX.',
    '.XXX....XXX.',
    'XX........XX',
    '............',
    '............',
  ],
  cog: [
    '....XXXX....',
    '.XX.XXXX.XX.',
    '.XXXXXXXXXX.',
    '..XXX..XXX..',
    'XXXX....XXXX',
    'XXX......XXX',
    'XXX......XXX',
    'XXXX....XXXX',
    '..XXX..XXX..',
    '.XXXXXXXXXX.',
    '.XX.XXXX.XX.',
    '....XXXX....',
  ],
  clock: [
    '...XXXXXX...',
    '..XX....XX..',
    '.XX..XX..XX.',
    '.X...XX...X.',
    'XX...XX...XX',
    'XX...XXXX.XX',
    'XX........XX',
    '.X........X.',
    '.XX......XX.',
    '..XX....XX..',
    '...XXXXXX...',
    '............',
  ],
  lock: [
    '...XXXXXX...',
    '..XX....XX..',
    '..XX....XX..',
    '..XX....XX..',
    '.XXXXXXXXXX.',
    '.XXXXXXXXXX.',
    '.XXXX..XXXX.',
    '.XXXX..XXXX.',
    '.XXXXXXXXXX.',
    '.XXXXXXXXXX.',
    '............',
    '............',
  ],
  dot: [
    '............',
    '............',
    '............',
    '....XXXX....',
    '...XXXXXX...',
    '...XXXXXX...',
    '...XXXXXX...',
    '...XXXXXX...',
    '....XXXX....',
    '............',
    '............',
    '............',
  ],
} as const;

export type IconName = keyof typeof ART;

const paths = new Map<IconName, string>();

function pathFor(name: IconName): string {
  let d = paths.get(name);
  if (d === undefined) {
    d = '';
    ART[name].forEach((row, y) => {
      // One rectangle per horizontal run of filled pixels.
      for (let x = 0; x < row.length; x++) {
        if (row[x] !== 'X') continue;
        let w = 1;
        while (row[x + w] === 'X') w++;
        d += `M${x} ${y}h${w}v1h-${w}z`;
        x += w;
      }
    });
    paths.set(name, d);
  }
  return d;
}

const SVG = 'http://www.w3.org/2000/svg';

/** An icon that takes the text colour of whatever it sits in. */
export function icon(name: IconName, className = ''): SVGSVGElement {
  const svg = document.createElementNS(SVG, 'svg');
  svg.setAttribute('viewBox', '0 0 12 12');
  svg.setAttribute('class', `ico${className ? ` ${className}` : ''}`);
  svg.setAttribute('aria-hidden', 'true');
  const path = document.createElementNS(SVG, 'path');
  path.setAttribute('d', pathFor(name));
  svg.append(path);
  return svg;
}

export function isIcon(name: string): name is IconName {
  return name in ART;
}
